local M = {}
local wt = require 'wezterm'
local home_dir = os.getenv('HOME')

-- Enable autogenerated colors from wallust
function M.enable(cfg)
	cfg.colors = 
		wt.color.load_scheme(home_dir .. "/.config/wezterm/assets/colors/Auto.toml")
end

return M
