alpha = 80
backend = "fastresize"
check_contrast = true
color_space = "lch-ansi"
palette = "ansidark16"
saturation = 70

[templates]
wezterm = { template = 'wezterm.toml', target = '~/.config/wezterm/assets/colors/Auto.toml' }
neovim = { template = 'nvim.json', target = '~/.config/nvim/colors.json' }
